name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      - name: Run tests (produce HTML + JUnit)
        id: tests
        env:
          CI: true
          # Set BASE_URL only if you really need to override it.
          # BASE_URL: ${{ secrets.BASE_URL }} # e.g. https://pokeapi.co/api/v2
        run: |
          mkdir -p reports/html
          npm run test:ci || true
          # Save exit code separately so we can still publish reports
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      # Publish JUnit summary only if file exists
      - name: Publish JUnit summary to PR
        if: always() && hashFiles('junit.xml') != ''
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: junit.xml
          detailed_summary: true
          check_name: Jest Tests

      # Upload HTML report if it exists
      - name: Upload HTML report
        if: always() && hashFiles('reports/html/index.html') != ''
        uses: actions/upload-artifact@v4
        with:
          name: html-report-node-${{ matrix.node }}
          path: reports/html

      # Upload JUnit XML if it exists
      - name: Upload JUnit XML
        if: always() && hashFiles('junit.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: junit-node-${{ matrix.node }}
          path: junit.xml

      # Finally, fail the job if tests actually failed
      - name: Set job status from test exit code
        if: always()
        run: |
          if [ "${{ steps.tests.outputs.exit_code }}" != "0" ]; then
            echo "Tests failed with exit code ${{ steps.tests.outputs.exit_code }}"
            exit 1
          fi
